from .v3_core import MIGRATIONS as CORE_MIGRATIONS
from .project_profit import MIGRATIONS as PROJECT_PROFIT_MIGRATIONS
from .procurement_tax_freight import MIGRATIONS as PROCUREMENT_TAX_FREIGHT_MIGRATIONS
from .project_site_integrity import MIGRATIONS as PROJECT_SITE_INTEGRITY_MIGRATIONS
from .v4_operations import MIGRATIONS as V4_OPERATIONS_MIGRATIONS
from .project_alias_normalization import MIGRATIONS as PROJECT_ALIAS_MIGRATIONS
from .labor_rate_adjustment import MIGRATIONS as LABOR_RATE_ADJUSTMENT_MIGRATIONS
from .ai_conversations import MIGRATIONS as AI_CONVERSATION_MIGRATIONS
from .cost_allocations import MIGRATIONS as COST_ALLOCATION_MIGRATIONS
from .invoice_revisions import MIGRATIONS as INVOICE_REVISION_MIGRATIONS
from .work_log_overtime import MIGRATIONS as WORK_LOG_OVERTIME_MIGRATIONS
from .work_log_project_attribution import MIGRATIONS as WORK_LOG_ATTRIBUTION_MIGRATIONS
from .invoice_settlement_links import MIGRATIONS as INVOICE_SETTLEMENT_LINK_MIGRATIONS
from .purchase_payment_allocations import MIGRATIONS as PURCHASE_PAYMENT_MIGRATIONS
from .data_integrity_indexes import MIGRATIONS as DATA_INTEGRITY_MIGRATIONS
from .construction_attachments import MIGRATIONS as CONSTRUCTION_ATTACHMENT_MIGRATIONS
from .business_partner_profiles import MIGRATIONS as BUSINESS_PARTNER_PROFILE_MIGRATIONS
from .cash_projects import MIGRATIONS as CASH_PROJECT_MIGRATIONS
from .receipt_revisions import MIGRATIONS as RECEIPT_REVISION_MIGRATIONS
from .purchase_cost_allocations import (
    MIGRATIONS as PURCHASE_COST_ALLOCATION_MIGRATIONS,
)
from .receipt_income_allocations import (
    MIGRATIONS as RECEIPT_INCOME_ALLOCATION_MIGRATIONS,
)

MIGRATIONS = [
    *CORE_MIGRATIONS,
    *PROJECT_PROFIT_MIGRATIONS,
    *PROCUREMENT_TAX_FREIGHT_MIGRATIONS,
    *PROJECT_SITE_INTEGRITY_MIGRATIONS,
    *V4_OPERATIONS_MIGRATIONS,
    *PROJECT_ALIAS_MIGRATIONS,
    *LABOR_RATE_ADJUSTMENT_MIGRATIONS,
    *AI_CONVERSATION_MIGRATIONS,
    *COST_ALLOCATION_MIGRATIONS,
    *INVOICE_REVISION_MIGRATIONS,
    *WORK_LOG_OVERTIME_MIGRATIONS,
    *WORK_LOG_ATTRIBUTION_MIGRATIONS,
    *INVOICE_SETTLEMENT_LINK_MIGRATIONS,
    *PURCHASE_PAYMENT_MIGRATIONS,
    *DATA_INTEGRITY_MIGRATIONS,
    *CONSTRUCTION_ATTACHMENT_MIGRATIONS,
    *BUSINESS_PARTNER_PROFILE_MIGRATIONS,
    *CASH_PROJECT_MIGRATIONS,
    *RECEIPT_REVISION_MIGRATIONS,
    *PURCHASE_COST_ALLOCATION_MIGRATIONS,
    *RECEIPT_INCOME_ALLOCATION_MIGRATIONS,
]

__all__ = ["MIGRATIONS"]
