from .v3_core import MIGRATIONS as CORE_MIGRATIONS
from .project_profit import MIGRATIONS as PROJECT_PROFIT_MIGRATIONS
from .procurement_tax_freight import MIGRATIONS as PROCUREMENT_TAX_FREIGHT_MIGRATIONS
from .project_site_integrity import MIGRATIONS as PROJECT_SITE_INTEGRITY_MIGRATIONS
from .v4_operations import MIGRATIONS as V4_OPERATIONS_MIGRATIONS
from .project_alias_normalization import MIGRATIONS as PROJECT_ALIAS_MIGRATIONS
from .labor_rate_adjustment import MIGRATIONS as LABOR_RATE_ADJUSTMENT_MIGRATIONS
from .ai_conversations import MIGRATIONS as AI_CONVERSATION_MIGRATIONS
from .cost_allocations import MIGRATIONS as COST_ALLOCATION_MIGRATIONS
from .invoice_revisions import MIGRATIONS as INVOICE_REVISION_MIGRATIONS
from .work_log_overtime import MIGRATIONS as WORK_LOG_OVERTIME_MIGRATIONS
from .work_log_project_attribution import MIGRATIONS as WORK_LOG_ATTRIBUTION_MIGRATIONS
from .invoice_settlement_links import MIGRATIONS as INVOICE_SETTLEMENT_LINK_MIGRATIONS
from .purchase_payment_allocations import MIGRATIONS as PURCHASE_PAYMENT_MIGRATIONS
from .data_integrity_indexes import MIGRATIONS as DATA_INTEGRITY_MIGRATIONS
from .construction_attachments import MIGRATIONS as CONSTRUCTION_ATTACHMENT_MIGRATIONS
from .business_partner_profiles import MIGRATIONS as BUSINESS_PARTNER_PROFILE_MIGRATIONS
from .cash_projects import MIGRATIONS as CASH_PROJECT_MIGRATIONS
from .receipt_revisions import MIGRATIONS as RECEIPT_REVISION_MIGRATIONS
from .purchase_cost_allocations import (
    MIGRATIONS as PURCHASE_COST_ALLOCATION_MIGRATIONS,
)
from .receipt_income_allocations import (
    MIGRATIONS as RECEIPT_INCOME_ALLOCATION_MIGRATIONS,
)
from .contract_pricing_modes import MIGRATIONS as CONTRACT_PRICING_MODE_MIGRATIONS
from .contract_project_links import MIGRATIONS as CONTRACT_PROJECT_LINK_MIGRATIONS
from .cash_project_limits import MIGRATIONS as CASH_PROJECT_LIMIT_MIGRATIONS
from .receipt_allocation_status import (
    MIGRATIONS as RECEIPT_ALLOCATION_STATUS_MIGRATIONS,
)
from .cash_contract_cleanup import MIGRATIONS as CASH_CONTRACT_CLEANUP_MIGRATIONS
from .cash_contract_restore import MIGRATIONS as CASH_CONTRACT_RESTORE_MIGRATIONS
from .invoice_receipt_fifo import MIGRATIONS as INVOICE_RECEIPT_FIFO_MIGRATIONS
from .ai_feedback import MIGRATIONS as AI_FEEDBACK_MIGRATIONS
from .collection_followups import MIGRATIONS as COLLECTION_FOLLOWUP_MIGRATIONS
from .cost_revisions import MIGRATIONS as COST_REVISION_MIGRATIONS

from .purchase_price_basis import MIGRATIONS as PURCHASE_PRICE_BASIS_MIGRATIONS

MIGRATIONS = [
    *CORE_MIGRATIONS,
    *PROJECT_PROFIT_MIGRATIONS,
    *PROCUREMENT_TAX_FREIGHT_MIGRATIONS,
    *PROJECT_SITE_INTEGRITY_MIGRATIONS,
    *V4_OPERATIONS_MIGRATIONS,
    *PROJECT_ALIAS_MIGRATIONS,
    *LABOR_RATE_ADJUSTMENT_MIGRATIONS,
    *AI_CONVERSATION_MIGRATIONS,
    *COST_ALLOCATION_MIGRATIONS,
    *INVOICE_REVISION_MIGRATIONS,
    *WORK_LOG_OVERTIME_MIGRATIONS,
    *WORK_LOG_ATTRIBUTION_MIGRATIONS,
    *INVOICE_SETTLEMENT_LINK_MIGRATIONS,
    *PURCHASE_PAYMENT_MIGRATIONS,
    *DATA_INTEGRITY_MIGRATIONS,
    *CONSTRUCTION_ATTACHMENT_MIGRATIONS,
    *BUSINESS_PARTNER_PROFILE_MIGRATIONS,
    *CASH_PROJECT_MIGRATIONS,
    *RECEIPT_REVISION_MIGRATIONS,
    *PURCHASE_COST_ALLOCATION_MIGRATIONS,
    *RECEIPT_INCOME_ALLOCATION_MIGRATIONS,
    *CONTRACT_PRICING_MODE_MIGRATIONS,
    *CONTRACT_PROJECT_LINK_MIGRATIONS,
    *CASH_PROJECT_LIMIT_MIGRATIONS,
    *RECEIPT_ALLOCATION_STATUS_MIGRATIONS,
    *CASH_CONTRACT_CLEANUP_MIGRATIONS,
    *CASH_CONTRACT_RESTORE_MIGRATIONS,
    *INVOICE_RECEIPT_FIFO_MIGRATIONS,
    *AI_FEEDBACK_MIGRATIONS,
    *COLLECTION_FOLLOWUP_MIGRATIONS,
    *COST_REVISION_MIGRATIONS,
    *PURCHASE_PRICE_BASIS_MIGRATIONS,
]

from .supplier_kind import MIGRATIONS as SUPPLIER_KIND_MIGRATIONS
MIGRATIONS.extend(SUPPLIER_KIND_MIGRATIONS)

__all__ = ["MIGRATIONS"]
from .purchase_settlement_modes import MIGRATIONS as PURCHASE_SETTLEMENT_MIGRATIONS
MIGRATIONS.extend(PURCHASE_SETTLEMENT_MIGRATIONS)

from .funds_management import MIGRATIONS as FUNDS_MANAGEMENT_MIGRATIONS
MIGRATIONS.extend(FUNDS_MANAGEMENT_MIGRATIONS)

from .cash_budget import MIGRATIONS as CASH_BUDGET_MIGRATIONS
MIGRATIONS.extend(CASH_BUDGET_MIGRATIONS)

from .historical_receivables import MIGRATIONS as HISTORICAL_RECEIVABLE_MIGRATIONS
MIGRATIONS.extend(HISTORICAL_RECEIVABLE_MIGRATIONS)

from .historical_receipt_payer import MIGRATIONS as HISTORICAL_RECEIPT_PAYER_MIGRATIONS
MIGRATIONS.extend(HISTORICAL_RECEIPT_PAYER_MIGRATIONS)

from .invoice_income import MIGRATIONS as INVOICE_INCOME_MIGRATIONS
MIGRATIONS.extend(INVOICE_INCOME_MIGRATIONS)

from .advance_receipts import MIGRATIONS as ADVANCE_RECEIPT_MIGRATIONS
MIGRATIONS.extend(ADVANCE_RECEIPT_MIGRATIONS)

from .cash_collection_closure import MIGRATIONS as CASH_CLOSURE_MIGRATIONS
MIGRATIONS.extend(CASH_CLOSURE_MIGRATIONS)

from .purchase_order_status_codes import MIGRATIONS as PURCHASE_ORDER_STATUS_MIGRATIONS
MIGRATIONS.extend(PURCHASE_ORDER_STATUS_MIGRATIONS)

from .invoice_tax_amounts import MIGRATIONS as INVOICE_TAX_MIGRATIONS
MIGRATIONS.extend(INVOICE_TAX_MIGRATIONS)
